extension String {
    var i18n: String {
        return PaymentStrings.get(self)
    }
}

class PaymentStrings {
    
    static func get(_ key: String) -> String {
        let locale = WonderPayment.paymentConfig.locale
        let res: Dictionary<String, String>
        switch (locale) {
        case .en_US:
            res = en_US
        case .zh_CN:
            res = zh_CN
        case .zh_HK:
            res = zh_HK
        }
        return res[key] ?? key
        
    }
    
    static let en_US = [
        "paymentMethod": "Payment method",
        "selectPaymentMethod": "Select a payment method",
        "securedCheckout": "Secured Checkout",
        "serviceFee": "$0 Service Fee",
        "streetHailPay": "Scan for Street Hail Pay",
        "unfinishedPayment": "Unfinished Payment",
        "whySeeingThis": "Why am I seeing this?",
        "payment": "Payment",
        "status": "Status",
        "pending": "Pending",
        "initiatedAt": "Payment initiated at",
        "pendingPayment": "Pending Payment Status",
        "pendingPaymentDesc":
"""
The reason why you're seeing this status is because there might be a pending payment initiated (commonly when you initiate Wechat Pay or Alipay). What to do:

 1. If you have successfully made the payment, please come back and check the payment status shortly later.

 2. If you have dropped out of the payment process, you can either complete the unfinished payment or make another payment.
""",
        "paymentFailed": "Payment failed. Please try again",
        "retryPayment": "Retry Payment",
        "successfulPayment": "Successful Payment",
        "successfulPreAuth": "Successful\nPre-authorisation",
        "card": "Card",
        "date": "Date",
        "totalAmount": "Total Amount",
        "cardNumber": "Card Number",
        "inputCardNumber": "Input Card Number",
        "expiryDate": "Expiry Date",
        "firstName": "Cardholder First Name",
        "inputFirstName": "Input Cardholder First Name",
        "lastName": "Cardholder Last Name",
        "inputLastName":"Input Cardholder Last Name",
        "phoneNumber": "Cardholder Phone Number",
        "inputPhoneNumber": "Input Phone Number",
        "saveCardInfo": "Save this Card Information",
        "confirm": "Confirm",
        "cardPayment": "Card Payment",
        "back": "Back",
        "dialingCode": "Dialing Code",
        "search":"Search",
        "cvv": "CVV",
        "pay": "Pay",
        "wechatPay": "Wechat Pay",
        "alipay": "Alipay",
        "alipayHK": "Alipay HK",
        "applePay": "Apple Pay",
        "unionPay": "UnionPay Wallet",
        "octopus": "Octopus",
        "cancel": "Cancel",
        "save": "Save",
        "networkError": "Network Error",
        "unknownError": "Unknown Error",
        "dataFormatError": "Data Format Error",
        "3dsVerificationFailed": "3DS Verification Failed",
        "unsupportedError": "Unsupported payment method!",
        "processing": "Processing The Transaction...",
        "doNotClose": "Please don't close or refresh",
        "willAutoRedirect": "This page will automatically redirect",
        "required": "Required",
        "enterValidNumber": "Please enter a valid credit card number",
        "enterValidExpiry": "Enter valid expiry date",
        "enterValidCVV": "Enter valid CVV",
        "nameShouldNot": "Name should not include numbers and special characters",
        "invalidPhone": "Invalid Phone Number",
        "saveThisCard": "Save this Card",
        "cardVerified": "Card verified",
        "canStartPaying": "You can start paying with this card",
        "closeSession": "Close Payment Session?",
        "sureToLeave": "You haven’t finished the payment.Are you sure you want to leave?",
        "continuePayment": "Continue the Payment",
        "paymentAmount": "Payment Amount",
        "transactionID": "Transaction ID",
        "RRN": "RRN",
        "customerName": "Customer Name",
        "transactionTime": "Transaction Time",
        "invoiceAmount": "Invoice Amount",
        "preAuthAmount": "Pre-auth Amount",
        "payingWith": "Paying with %@",
        "canPayUsing": "You can pay using the %@ account connected to this device.",
        "issuer": "Issuer",
        "holderName": "Holder Name",
        "deleteThisCard": "Delete this Card",
        "deleteCard": "Delete Card",
        "sureDeleteThisCard": "Are you sure to delete this card? The action is irreversible",
        "cardDeleted": "Card Deleted",
        "cardDeletedSuccess": "Card Deleted Successfully",
        "availablePaymentMethod": "Available Payment Method",
        "preAuthPaymentMethod": "Pre-authorise Payment Method",
        "thisIsPreAuth": "ⓘ This is a pre-authorized charge",
        "amountAdjustment": "Payment Amount Adjustment",
        "amountAdjustmentDesc": "Due to Octopus Payment’s rule, all payment amount needs to be adjusted to 1 decimal value. Hence, if you wish to proceed with Octopus payment, this original payment of %@ will be rounded up to %@",
    ]
    
    static let zh_CN = [
        "paymentMethod": "支付方式",
        "selectPaymentMethod": "选择一种支付方式",
        "securedCheckout": "安全结帐",
        "serviceFee": "$0 行政费",
        "streetHailPay": "扫码街车付款",
        "unfinishedPayment": "未完成付款",
        "whySeeingThis": "为什么我会看到这个？",
        "payment": "支付方式",
        "status": "支付状态",
        "pending": "未完成",
        "initiatedAt": "支付创建",
        "pendingPayment": "待支付状态",
        "pendingPaymentDesc":
"""
您看到这个状态的原因可能是因为有待支付的款项（通常是当您启动微信支付或支付宝时）。处理方法如下：

 1. 如果您已成功完成支付，请稍后回来检查支付状态。

 2. 如果您中途放弃了支付流程，您可以选择完成未完成的支付，或进行另一笔支付。
""",
        "paymentFailed": "支付失败，请再试一次",
        "retryPayment": "重新支付",
        "successfulPayment": "支付成功",
        "successfulPreAuth": "预授权成功",
        "card": "卡",
        "date": "日期",
        "totalAmount": "总金额",
        "cardNumber": "信用卡号码",
        "inputCardNumber": "请输入信用卡号码",
        "expiryDate": "有效期",
        "firstName": "持卡人姓氏",
        "inputFirstName": "请输入持卡人姓氏",
        "lastName": "持卡人名字",
        "inputLastName":"请输入持卡人名字",
        "phoneNumber": "持卡人手机号",
        "inputPhoneNumber": "请输入手机号",
        "saveCardInfo": "保存卡片信息",
        "confirm": "确定",
        "cardPayment": "信用卡支付",
        "back": "返回",
        "dialingCode": "区号",
        "search":"搜索",
        "cvv": "CVV",
        "pay": "付款",
        "wechatPay": "微信支付",
        "alipay": "支付宝",
        "alipayHK": "支付宝 香港",
        "unionPay": "云闪付",
        "applePay": "Apple Pay",
        "octopus": "八达通",
        "cancel": "取消",
        "save": "保存",
        "networkError": "网络异常",
        "unknownError": "未知异常",
        "dataFormatError": "数据格式错误",
        "3dsVerificationFailed": "3DS验证未通过",
        "unsupportedError": "无法使用该支付方式",
        "processing": "交易处理中...",
        "doNotClose": "请不要关闭或刷新页面",
        "willAutoRedirect": "页面将自动跳转",
        "required": "必填",
        "enterValidNumber": "请输入一个有效的信用卡号码",
        "enterValidExpiry": "请输入有效的到期日期",
        "enterValidCVV": "请输入有效的CVV",
        "nameShouldNot": "姓名不能包含数字和特殊字符",
        "invalidPhone": "无效的手机号码",
        "saveThisCard": "保存卡片",
        "cardVerified": "卡片已验证",
        "canStartPaying": "您可以开始用这张卡付款",
        "closeSession": "关闭付款会话？",
        "sureToLeave": "您尚未完成付款。您确定要离开吗？",
        "continuePayment": "继续付款",
        "paymentAmount": "付款金额",
        "transactionID": "交易ID",
        "RRN":"RRN",
        "customerName": "客户名称",
        "transactionTime": "交易时间",
        "invoiceAmount": "发票金额",
        "preAuthAmount": "预授权金额",
        "payingWith": "使用%@付款",
        "canPayUsing": "您可以使用连接到该设备的%@账户进行支付",
        "issuer":"发卡行",
        "holderName": "持有人姓名",
        "deleteThisCard": "删除这张卡",
        "deleteCard": "删除卡片",
        "sureDeleteThisCard": "您确定删除这张卡吗？该操作不可逆",
        "cardDeleted": "卡片已删除",
        "cardDeletedSuccess": "卡片删除成功",
        "availablePaymentMethod": "可用的支付方式",
        "preAuthPaymentMethod": "预授权支付方式",
        "thisIsPreAuth": "ⓘ 这是预授权的费用",
        "amountAdjustment": "支付金额调整",
        "amountAdjustmentDesc": "由于八达通付款规则，所有付款金额需要调整为仅保留一位小数。因此，如果您想继续使用八达通付款，则原本支付的 %@ 将被调整为 %@",
    ]
    
    static let zh_HK = [
        "paymentMethod": "支付方式",
        "selectPaymentMethod": "選擇一種支付方式",
        "securedCheckout": "安全結帳",
        "serviceFee": "$0 行政費",
        "streetHailPay": "掃碼街車付款",
        "unfinishedPayment": "未完成付款",
        "whySeeingThis": "為什麼我會看到這個？",
        "payment": "支付方式",
        "status": "支付狀態",
        "pending": "未完成",
        "initiatedAt": "支付創建",
        "pendingPayment": "待支付狀態",
        "pendingPaymentDesc":
"""
您看到這個狀態的原因可能是因為有待支付的款項（通常是當您啟動微信支付或支付寶時）。處理方法如下：

 1. 如果您已成功完成支付，請稍後回來檢查支付狀態。

 2. 如果您中途放棄了支付流程，您可以選擇完成未完成的支付，或進行另一筆支付。
""",
        "paymentFailed": "支付失敗，請再試一次",
        "retryPayment": "重新支付",
        "successfulPayment": "支付成功",
        "successfulPreAuth": "預授權成功",
        "card": "卡",
        "date": "日期",
        "totalAmount": "總金額",
        "cardNumber": "信用卡號碼",
        "inputCardNumber": "請輸入信用卡號碼",
        "expiryDate": "有效期",
        "firstName": "持卡人姓氏",
        "inputFirstName": "請輸入持卡人姓氏",
        "lastName": "持卡人名字",
        "inputLastName":"請輸入持卡人名字",
        "phoneNumber": "持卡人手機號碼",
        "inputPhoneNumber": "請輸入手機號碼",
        "saveCardInfo": "保存卡片信息",
        "confirm": "確定",
        "cardPayment": "信用卡支付",
        "back": "返回",
        "dialingCode": "區號",
        "search":"搜索",
        "cvv": "CVV",
        "pay": "付款",
        "wechatPay": "微信支付",
        "alipay": "支付寶",
        "alipayHK": "支付寶 香港",
        "unionPay": "雲閃付",
        "applePay": "Apple Pay",
        "octopus": "八達通",
        "cancel": "取消",
        "save": "保存",
        "networkError": "網絡異常",
        "unknownError": "未知異常",
        "dataFormatError": "數據格式錯誤",
        "3dsVerificationFailed": "3DS驗證未通過",
        "unsupportedError": "無法使用該付款方式",
        "processing": "交易處理中...",
        "doNotClose": "請不要關閉或刷新頁面",
        "willAutoRedirect": "頁面將自動跳轉",
        "required": "必填",
        "enterValidNumber": "請輸入一個有效的信用卡號碼",
        "enterValidExpiry": "請輸入有效的到期日期",
        "enterValidCVV": "請輸入有效的CVV",
        "nameShouldNot": "姓名不能包含數字和特殊字符",
        "invalidPhone": "無效的手機號碼",
        "saveThisCard": "保存卡片",
        "cardVerified": "卡片已驗證",
        "canStartPaying": "您可以開始用這張卡付款",
        "closeSession": "關閉付款會話？",
        "sureToLeave": "您尚未完成付款。您確定要離開嗎？",
        "continuePayment": "繼續付款",
        "paymentAmount": "付款金額",
        "transactionID": "交易ID",
        "RRN": "RRN",
        "customerName": "客戶名稱",
        "transactionTime": "交易時間",
        "invoiceAmount": "發票金額",
        "preAuthAmount": "預授權金額",
        "payingWith": "使用%@付款",
        "canPayUsing": "您可以使用連接到該設備的%@帳戶進行支付",
        "issuer":"發卡行",
        "holderName": "持有人姓名",
        "deleteThisCard": "刪除這張卡",
        "deleteCard": "刪除卡片",
        "sureDeleteThisCard": "您確定刪除這張卡嗎？該操作不可逆",
        "cardDeleted": "卡片已刪除",
        "cardDeletedSuccess": "卡片刪除成功",
        "availablePaymentMethod": "可用的支付方式",
        "preAuthPaymentMethod": "預授權支付方式",
        "thisIsPreAuth": "ⓘ 這是預授權的費用",
        "amountAdjustment": "支付金額調整",
        "amountAdjustmentDesc": "由於八達通付款規則，所有付款金額需要調整為僅保留一位小數。因此，如果您想繼續使用八達通付款，則原本支付的 %@ 將被調整為 %@",
    ]
}
